### ISSUE TITLE
USER STORY: Love Running Poll Feature

### ISSUE THREAD

**Issue by JackH1155** [JackH1155/love-running#1]
As a **customer** I can **give me opinion and/or feedback** so that **users looking at the site can see what other runners think**

## Acceptance Criteria:

1. The option should be on the front page as to be one of the first things people see
2. The poll should be have options for different tracks and times.
3. The user should be able to show or hide there username on the poll through a checkbox.
4.  The user should get a confirmation when the have submitted there feedback.

## Tasks:
- [ ]  Add a form with the field of username, best time to run & best track to run 
- [ ] Add submit button
- [ ] Add Anonymous checkbox
- [ ] Test the work to see if preforms correctly
